# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a20308a28b900656a2041a56003c98a960e934fdb2308682d3c2d0671ff377e766e579739fe56ec43ab206479a8b56ed9e347daf8bee0720af21deb58a7114

test:
  secret_key_base: 438e77fa373f8d86ed1d067fb96b40a227b74464b075e5559f54dff5159c36316812c5ed7ad570a71ac16558d1f8c86dc1eceefcc8a57fa7668d63e83b0285ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
